version: 2

updates:
  - package-ecosystem: pub
    directory: auth0_flutter
    schedule:
      interval: daily
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    labels:
      - ignore title check
      - dependencies

  - package-ecosystem: pub
    directory: auth0_flutter/example
    schedule:
      interval: daily
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    labels:
      - ignore title check
      - dependencies

  - package-ecosystem: pub
    directory: auth0_flutter_platform_interface
    schedule:
      interval: daily
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    labels:
      - ignore title check
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - ignore title check
      - dependencies

  - package-ecosystem: github-actions
    directory: /.github/actions/rl-scanner
    schedule:
      interval: daily
    labels:
      - ignore title check
      - dependencies

  - package-ecosystem: github-actions
    directory: /.github/actions/setup-android
    schedule:
      interval: daily
    labels:
      - ignore title check
      - dependencies

  - package-ecosystem: github-actions
    directory: /.github/actions/setup-darwin
    schedule:
      interval: daily
    labels:
      - ignore title check
      - dependencies

  - package-ecosystem: github-actions
    directory: /.github/actions/setup-publish
    schedule:
      interval: daily
    labels:
      - ignore title check
      - dependencies

  - package-ecosystem: github-actions
    directory: /.github/actions/smoke-tests-darwin
    schedule:
      interval: daily
    labels:
      - ignore title check
      - dependencies

  - package-ecosystem: github-actions
    directory: /.github/actions/unit-tests-darwin
    schedule:
      interval: daily
    labels:
      - ignore title check
      - dependencies
